Update Trigger in sequence.yml

diff --git a/.github/workflows/Trigger in sequence.yml b/.github/workflows/Trigger in sequence.yml
--- a/.github/workflows/Trigger in sequence.yml
+++ b/.github/workflows/Trigger in sequence.yml
@@ -6,8 +6,134 @@ on:
     - cron: '*/20 * * * *'  # 每20分钟触发一次
 
 jobs:
+  trigger_adblock_rule_generator_shadowrocket_conf:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3  # 检出仓库代码
+
+      - name: Trigger and verify Run_AdBlock_Rule_Generator_shadowrocket_Conf
+        env:
+          TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          workflow_id="Run_AdBlock_Rule_Generator_shadowrocket_Conf.yml"
+          ref="main"
+          # 触发工作流
+          response=$(curl -X POST -H "Authorization: token $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
+            -d "{\"ref\":\"$ref\"}")
+          echo "Triggered workflow $workflow_id: $response"
+
+          # 验证工作流成功触发
+          while : ; do
+            status=$(curl -s -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
+              | jq -r '.workflow_runs[0].conclusion')
+
+            if [[ "$status" == "success" ]]; then
+              echo "Workflow $workflow_id completed successfully."
+              break
+            elif [[ "$status" == "failure" ]]; then
+              echo "Workflow $workflow_id failed."
+              exit 1
+            else
+              echo "Waiting for workflow $workflow_id to complete..."
+              sleep 30
+            fi
+          done
+
+          # 等待90秒
+          sleep 90
+
+  trigger_adblock_rule_generator_shadowrocket_txt:
+    runs-on: ubuntu-latest
+    needs: trigger_adblock_rule_generator_shadowrocket_conf
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3  # 检出仓库代码
+
+      - name: Trigger and verify Run_AdBlock_Rule_Generator_Shadowrock_Txt
+        env:
+          TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          workflow_id="Run_AdBlock_Rule_Generator_Shadowrock_Txt.yml"
+          ref="main"
+          # 触发工作流
+          response=$(curl -X POST -H "Authorization: token $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
+            -d "{\"ref\":\"$ref\"}")
+          echo "Triggered workflow $workflow_id: $response"
+
+          # 验证工作流成功触发
+          while : ; do
+            status=$(curl -s -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
+              | jq -r '.workflow_runs[0].conclusion')
+
+            if [[ "$status" == "success" ]]; then
+              echo "Workflow $workflow_id completed successfully."
+              break
+            elif [[ "$status" == "failure" ]]; then
+              echo "Workflow $workflow_id failed."
+              exit 1
+            else
+              echo "Waiting for workflow $workflow_id to complete..."
+              sleep 30
+            fi
+          done
+
+          # 等待90秒
+          sleep 90
+
+  trigger_adblock_rule_generator_shadowrocket_list:
+    runs-on: ubuntu-latest
+    needs: trigger_adblock_rule_generator_shadowrocket_txt
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3  # 检出仓库代码
+
+      - name: Trigger and verify Run_AdBlock_Rule_Generator_Shadowrocket_List
+        env:
+          TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          workflow_id="Run_AdBlock_Rule_Generator_Shadowrocket_List.yml"
+          ref="main"
+          # 触发工作流
+          response=$(curl -X POST -H "Authorization: token $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
+            -d "{\"ref\":\"$ref\"}")
+          echo "Triggered workflow $workflow_id: $response"
+
+          # 验证工作流成功触发
+          while : ; do
+            status=$(curl -s -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
+              | jq -r '.workflow_runs[0].conclusion')
+
+            if [[ "$status" == "success" ]]; then
+              echo "Workflow $workflow_id completed successfully."
+              break
+            elif [[ "$status" == "failure" ]]; then
+              echo "Workflow $workflow_id failed."
+              exit 1
+            else
+              echo "Waiting for workflow $workflow_id to complete..."
+              sleep 30
+            fi
+          done
+
+          # 等待90秒
+          sleep 90
+
   trigger_adblock_rule_generator_shadowrocket_yaml:
     runs-on: ubuntu-latest
+    needs: trigger_adblock_rule_generator_shadowrocket_list
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3  # 检出仓库代码
@@ -47,18 +173,18 @@ jobs:
           # 等待90秒
           sleep 90
 
-  trigger_adblock_rule_generator_txt:
+  trigger_adblock_rule_generator_txt_rule:
     runs-on: ubuntu-latest
     needs: trigger_adblock_rule_generator_shadowrocket_yaml
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3  # 检出仓库代码
 
-      - name: Trigger and verify Run_AdBlock_Rule_Generator_TXT
+      - name: Trigger and verify Run_AdBlock_Rule_Generator_TXT_RULE
         env:
           TOKEN: ${{ secrets.TOKEN }}
         run: |
-          workflow_id="Run_AdBlock_Rule_Generator_TXT.yml"
+          workflow_id="Run_AdBlock_Rule_Generator_TXT_RULE.yml"
           ref="main"
           # 触发工作流
           response=$(curl -X POST -H "Authorization: token $TOKEN" \
@@ -89,93 +215,9 @@ jobs:
           # 等待90秒
           sleep 90
 
-  trigger_adblock_rule_generator_list:
+  release_adblock_files:
     runs-on: ubuntu-latest
-    needs: trigger_adblock_rule_generator_txt
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3  # 检出仓库代码
-
-      - name: Trigger and verify Run_AdBlock_Rule_Generator_LIST
-        env:
-          TOKEN: ${{ secrets.TOKEN }}
-        run: |
-          workflow_id="Run_AdBlock_Rule_Generator_LIST.yml"
-          ref="main"
-          # 触发工作流
-          response=$(curl -X POST -H "Authorization: token $TOKEN" \
-            -H "Accept: application/vnd.github.v3+json" \
-            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
-            -d "{\"ref\":\"$ref\"}")
-          echo "Triggered workflow $workflow_id: $response"
-
-          # 验证工作流成功触发
-          while : ; do
-            status=$(curl -s -H "Authorization: token $TOKEN" \
-              -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
-              | jq -r '.workflow_runs[0].conclusion')
-
-            if [[ "$status" == "success" ]]; then
-              echo "Workflow $workflow_id completed successfully."
-              break
-            elif [[ "$status" == "failure" ]]; then
-              echo "Workflow $workflow_id failed."
-              exit 1
-            else
-              echo "Waiting for workflow $workflow_id to complete..."
-              sleep 30
-            fi
-          done
-
-          # 等待90秒
-          sleep 90
-
-  trigger_adblock_rule_generator_yaml:
-    runs-on: ubuntu-latest
-    needs: trigger_adblock_rule_generator_list
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3  # 检出仓库代码
-
-      - name: Trigger and verify Run_AdBlock_Rule_Generator_YAML
-        env:
-          TOKEN: ${{ secrets.TOKEN }}
-        run: |
-          workflow_id="Run_AdBlock_Rule_Generator_YAML.yml"
-          ref="main"
-          # 触发工作流
-          response=$(curl -X POST -H "Authorization: token $TOKEN" \
-            -H "Accept: application/vnd.github.v3+json" \
-            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
-            -d "{\"ref\":\"$ref\"}")
-          echo "Triggered workflow $workflow_id: $response"
-
-          # 验证工作流成功触发
-          while : ; do
-            status=$(curl -s -H "Authorization: token $TOKEN" \
-              -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
-              | jq -r '.workflow_runs[0].conclusion')
-
-            if [[ "$status" == "success" ]]; then
-              echo "Workflow $workflow_id completed successfully."
-              break
-            elif [[ "$status" == "failure" ]]; then
-              echo "Workflow $workflow_id failed."
-              exit 1
-            else
-              echo "Waiting for workflow $workflow_id to complete..."
-              sleep 30
-            fi
-          done
-
-          # 等待90秒
-          sleep 90
-
-  trigger_release_adblock_files:
-    runs-on: ubuntu-latest
-    needs: trigger_adblock_rule_generator_yaml
+    needs: trigger_adblock_rule_generator_txt_rule
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3  # 检出仓库代码
@@ -212,18 +254,3 @@ jobs:
             fi
           done
 
-          # 等待90秒
-          sleep 90
-
-  check_all_workflows:
-    runs-on: ubuntu-latest
-    needs: 
-      - trigger_adblock_rule_generator_shadowrocket_yaml
-      - trigger_adblock_rule_generator_txt
-      - trigger_adblock_rule_generator_list
-      - trigger_adblock_rule_generator_yaml
-      - trigger_release_adblock_files
-    steps:
-      - name: Ensure all workflows succeeded
-        run: |
-          echo "All workflows completed successfully"
